### ISSUE TITLE
Grafana 4.4.x

### ISSUE THREAD

**Issue by logicall** [raintank/snap-app#10]
Hello!
There will be a plugin for snap to support the version of grafana 4.4.x and higher.
I tried to use it on version 4.4.1.
The datasource has been added. But the data from snap does not get. I watched the sniffer - requests to the port api to snap from the grafana do not come

**Comment by morciari** [comment]
I did some tests with Grafana 4.4.1 and it seems to work.

**Comment by logicall** [comment]
Really works.
Thank you!
