### ISSUE TITLE
having trouble installing snap-app using grafana cli

### ISSUE THREAD

**Issue by theluke55** [raintank/snap-app#3]
# ./bin/grafana-cli plugins install raintank-snap-app

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4879fa]

goroutine 1 [running]:
panic(0x6e34a0, 0xc4200120a0)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/grafana/grafana/pkg/cmd/grafana-cli/services.createRequest(0xc4200f7740, 0x1f, 0xc420104690, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
    /root/work/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/services/services.go:152 +0x35a
github.com/grafana/grafana/pkg/cmd/grafana-cli/services.GetPlugin(0x7ffe5c5b85d9, 0x11, 0xc4200f7740, 0x1f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /root/work/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/services/services.go:115 +0xdf
github.com/grafana/grafana/pkg/cmd/grafana-cli/commands.InstallPlugin(0x7ffe5c5b85d9, 0x11, 0x0, 0x0, 0x88ca80, 0xc42004e048, 0x8, 0x727560)
    /root/work/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/commands/install_command.go:61 +0x89
github.com/grafana/grafana/pkg/cmd/grafana-cli/commands.installCommand(0x88ca80, 0xc42004e048, 0x733a65, 0x5)
    /root/work/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/commands/install_command.go:57 +0x10e
github.com/grafana/grafana/pkg/cmd/grafana-cli/commands.runCommand.func1(0xc4200af320)
    /root/work/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/commands/commands.go:15 +0x87
github.com/grafana/grafana/vendor/github.com/codegangsta/cli.Command.Run(0x7342be, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x741648, 0x2f, 0x0, ...)
    /root/work/src/github.com/grafana/grafana/vendor/github.com/codegangsta/cli/command.go:137 +0xa8b
github.com/grafana/grafana/vendor/github.com/codegangsta/cli.(_App).RunAsSubcommand(0xc4200af0e0, 0xc4200aefc0, 0x0, 0x0)
    /root/work/src/github.com/grafana/grafana/vendor/github.com/codegangsta/cli/app.go:283 +0x8c7
github.com/grafana/grafana/vendor/github.com/codegangsta/cli.Command.startApp(0x73430b, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x73aa38, 0x1a, 0x0, ...)
    /root/work/src/github.com/grafana/grafana/vendor/github.com/codegangsta/cli/command.go:215 +0x6e6
github.com/grafana/grafana/vendor/github.com/codegangsta/cli.Command.Run(0x73430b, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x73aa38, 0x1a, 0x0, ...)
    /root/work/src/github.com/grafana/grafana/vendor/github.com/codegangsta/cli/command.go:59 +0x13ca
github.com/grafana/grafana/vendor/github.com/codegangsta/cli.(_App).Run(0xc4200aeea0, 0xc42000c2c0, 0x4, 0x4, 0x0, 0x0)
    /root/work/src/github.com/grafana/grafana/vendor/github.com/codegangsta/cli/app.go:176 +0x919
main.main()
    /root/work/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/main.go:50 +0x529

**Comment by bergquist** [comment]
@theluke55 what version of grafana are you using? This due to bad error handling in the cli tool when sending requests to grafana.net. Just rerun the install command today and it should be working.

**Comment by theluke55** [comment]
@bergquist Version 4.0.0-pre1 (commit: v3.1.0-1163-g1ce0b8f)

just re-ran didn't work, i'm gonna try a different version

**Comment by bergquist** [comment]
@theluke55 could you try running it from the bin folder?

ex ./grafana-cli plugins install raintank-snap-app

**Comment by theluke55** [comment]
@bergquist still 

# ./grafana-cli plugins install raintank-snap-app

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4879fa]

goroutine 1 [running]:
panic(0x6e34a0, 0xc4200120b0)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/grafana/grafana/pkg/cmd/grafana-cli/services.createRequest(0xc4200f7800, 0x1f, 0xc420104690, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
    /root/work/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/services/services.go:152 +0x35a
github.com/grafana/grafana/pkg/cmd/grafana-cli/services.GetPlugin(0x7ffce6df45cd, 0x11, 0xc4200f7800, 0x1f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /root/work/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/services/services.go:115 +0xdf
github.com/grafana/grafana/pkg/cmd/grafana-cli/commands.InstallPlugin(0x7ffce6df45cd, 0x11, 0x0, 0x0, 0x88ca80, 0xc42004e048, 0x8, 0x727560)
    /root/work/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/commands/install_command.go:61 +0x89
github.com/grafana/grafana/pkg/cmd/grafana-cli/commands.installCommand(0x88ca80, 0xc42004e048, 0x733a65, 0x5)
    /root/work/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/commands/install_command.go:57 +0x10e
github.com/grafana/grafana/pkg/cmd/grafana-cli/commands.runCommand.func1(0xc4200af440)
    /root/work/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/commands/commands.go:15 +0x87
github.com/grafana/grafana/vendor/github.com/codegangsta/cli.Command.Run(0x7342be, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x741648, 0x2f, 0x0, ...)
    /root/work/src/github.com/grafana/grafana/vendor/github.com/codegangsta/cli/command.go:137 +0xa8b
github.com/grafana/grafana/vendor/github.com/codegangsta/cli.(_App).RunAsSubcommand(0xc4200af200, 0xc4200af0e0, 0x0, 0x0)
    /root/work/src/github.com/grafana/grafana/vendor/github.com/codegangsta/cli/app.go:283 +0x8c7
github.com/grafana/grafana/vendor/github.com/codegangsta/cli.Command.startApp(0x73430b, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x73aa38, 0x1a, 0x0, ...)
    /root/work/src/github.com/grafana/grafana/vendor/github.com/codegangsta/cli/command.go:215 +0x6e6
github.com/grafana/grafana/vendor/github.com/codegangsta/cli.Command.Run(0x73430b, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x73aa38, 0x1a, 0x0, ...)
    /root/work/src/github.com/grafana/grafana/vendor/github.com/codegangsta/cli/command.go:59 +0x13ca
github.com/grafana/grafana/vendor/github.com/codegangsta/cli.(_App).Run(0xc4200aefc0, 0xc42000c300, 0x4, 0x4, 0x0, 0x0)
    /root/work/src/github.com/grafana/grafana/vendor/github.com/codegangsta/cli/app.go:176 +0x919
main.main()
    /root/work/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/main.go:50 +0x529

**Comment by theluke55** [comment]
@bergquist also, the bin folder that i'm running it from is a local location, at /root/work/src/github.com/grafana/grafana/bin

**Comment by bergquist** [comment]
@theluke55 can you download other plugins?

**Comment by theluke55** [comment]
@bergquist no i can't

**Comment by bergquist** [comment]
@theluke55 can you access https://grafana.net/api/plugins from your browser? or curl

**Comment by theluke55** [comment]
@bergquist yup

**Comment by theluke55** [comment]
@bergquist gives me a big list of son

**Comment by theluke55** [comment]
*json

**Comment by bergquist** [comment]
@theluke55 Any chance you could try the nightly build or master?

**Comment by theluke55** [comment]
@bergquist i downloaded the latest tar.gz file unzipped then ran comm ./grafana-cli plugins install raintank-snap-app  from the bin directory and same error

**Comment by bergquist** [comment]
@theluke55 you could please post the error message you got from the last try?

**Comment by theluke55** [comment]
./grafana-cli plugins install raintank-snap-app
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4879fa]

goroutine 1 [running]:
panic(0x6e3520, 0xc4200120b0)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/grafana/grafana/pkg/cmd/grafana-cli/services.createRequest(0xc4200f7640, 0x1f, 0xc420104690, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/services/services.go:152 +0x35a
github.com/grafana/grafana/pkg/cmd/grafana-cli/services.GetPlugin(0x7ffc0cd395db, 0x11, 0xc4200f7640, 0x1f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/services/services.go:115 +0xdf
github.com/grafana/grafana/pkg/cmd/grafana-cli/commands.InstallPlugin(0x7ffc0cd395db, 0x11, 0x0, 0x0, 0x88dac0, 0xc42004e048, 0x8, 0x727680)
    /go/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/commands/install_command.go:61 +0x89
github.com/grafana/grafana/pkg/cmd/grafana-cli/commands.installCommand(0x88dac0, 0xc42004e048, 0x733b65, 0x5)
    /go/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/commands/install_command.go:57 +0x10e
github.com/grafana/grafana/pkg/cmd/grafana-cli/commands.runCommand.func1(0xc4200af440)
    /go/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/commands/commands.go:15 +0x87
github.com/grafana/grafana/vendor/github.com/codegangsta/cli.Command.Run(0x7343be, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x741735, 0x2f, 0x0, ...)
    /go/src/github.com/grafana/grafana/vendor/github.com/codegangsta/cli/command.go:137 +0xa8b
github.com/grafana/grafana/vendor/github.com/codegangsta/cli.(_App).RunAsSubcommand(0xc4200af200, 0xc4200af0e0, 0x0, 0x0)
    /go/src/github.com/grafana/grafana/vendor/github.com/codegangsta/cli/app.go:283 +0x8c7
github.com/grafana/grafana/vendor/github.com/codegangsta/cli.Command.startApp(0x73440b, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x73ab48, 0x1a, 0x0, ...)
    /go/src/github.com/grafana/grafana/vendor/github.com/codegangsta/cli/command.go:215 +0x6e6
github.com/grafana/grafana/vendor/github.com/codegangsta/cli.Command.Run(0x73440b, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x73ab48, 0x1a, 0x0, ...)
    /go/src/github.com/grafana/grafana/vendor/github.com/codegangsta/cli/command.go:59 +0x13ca
github.com/grafana/grafana/vendor/github.com/codegangsta/cli.(_App).Run(0xc4200aefc0, 0xc42000c2c0, 0x4, 0x4, 0x0, 0x0)
    /go/src/github.com/grafana/grafana/vendor/github.com/codegangsta/cli/app.go:176 +0x919
main.main()
    /go/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/main.go:50 +0x529

**Comment by bergquist** [comment]
@theluke55 thank you for your patience! :) Ive just improved the error handling and logging a little bit. It will soon be available for download.

**Comment by theluke55** [comment]
@bergquist ok i just downloaded the latest and now I'm getting this error:

 ./grafana-cli plugins install raintank-snap-app
Failed to send requesterrorGet https://grafana.net/api/plugins/repo/raintank-snap-app: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Error: ✗ Failed to send request. error: Get https://grafana.net/api/plugins/repo/raintank-snap-app: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

NAME:
   Grafana cli plugins install - install <plugin id> <plugin version (optional)>

USAGE:
   Grafana cli plugins install [arguments...]

so it looks like something with my internet connection.  I am behind a proxy so i'll look into if i need to setup that for using the grafana cli tool

**Comment by bergquist** [comment]
The default timeout is 10s Could that be a problem for you?

**Comment by theluke55** [comment]
@bergquist it might be, i'm looking into this more today, After relaunching grafana, i noticed that i'm starting my server from /root/work/src/github.com/grafana/grafana/bin/grafana-server

is that the correct place to start my grafana server from?

when downloading the snap-app plugin, is it expecting me to have my server running from a different location?

**Comment by theluke55** [comment]
@bergquist now i'm running in /root/grafana-4.0.0-1477060614pre1/bin/grafana-server

because thats the latest tar and unzipped location of grafana that i'm using, checked git proxy and that seems to be fine, so looking at other proxy settings to see if that helps

**Comment by theluke55** [comment]
i did what this: https://github.com/grafana/grafana/issues/4530 thread suggested and didn't use the grafana-cli instead i manually downloaded the plugin using git clone into data/plugins https://github.com/raintank/snap-app

**Comment by torkelo** [comment]
closing this as it's not related to this plugin but grafana-cli
